version: "3.2"

services:
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - .:/var/www/html/:cached
            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - 8013:80
            - 444:443
        links:
            - 'php'
        volumes:
            - .:/var/www/html/
            - ./docker/nginx:/etc/nginx/conf.d

    mariadb:
        image: mariadb:10.3.9
        container_name: ${APP_NAME:?err}-mariadb
        restart: 'on-failure'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        ports:
            - 3308:3306
        volumes:
            - ${PWD}
